<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0-windows</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <ApplicationIcon />
        <StartupObject />
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\OxyPlot\OxyPlot.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="1.2.25" />
    </ItemGroup>
</Project>
