<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <TargetFrameworks>net9.0-windows</TargetFrameworks>
      <UseWPF>true</UseWPF>
      <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\OxyPlot.Wpf\OxyPlot.Wpf.csproj" />
    <ProjectReference Include="..\..\..\OxyPlot\OxyPlot.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="1.2.25" />
  </ItemGroup>
</Project>
